[build]
  command = "pnpm build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
