#!/usr/bin/env node
/**
 * Reads full-size JPEGs from src/assets/gallery, writes resized WebP + JPEG
 * to public/gallery/, and generates src/data/gallery-manifest.gen.ts
 */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const inputDir = path.join(root, "src/assets/gallery");
const outDir = path.join(root, "public/gallery");
const manifestFile = path.join(root, "src/data/gallery-manifest.gen.ts");

const WIDTHS = [640, 960, 1280, 1920];
const LIGHTBOX_MAX = 2048;

function stemFromFilename(filename) {
  const base = filename.replace(/\.[^.]+$/i, "");
  const normalized = base
    .replace(/\s*\(\s*(\d+)\s*\)\s*$/i, "-$1")
    .replace(/[^\w.-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  return normalized || "image";
}

function cameraFilenamePattern(baseWithoutExt) {
  return /^(DSC|IMG|DSCN|DCIM|DSF|MVI)[_ \-]?\d+$/i.test(baseWithoutExt.trim());
}

async function isUpToDate(jpegFiles) {
  try {
    const text = await fs.readFile(manifestFile, "utf8");
    const stemCount = [...text.matchAll(/stem:\s*"([^"]+)"/g)].length;
    if (stemCount !== jpegFiles.length || stemCount === 0) return false;
    for (const file of jpegFiles) {
      const stem = stemFromFilename(file);
      const probe = path.join(outDir, `${stem}-1920.webp`);
      try {
        await fs.access(probe);
      } catch {
        return false;
      }
    }
    const inStat = await fs.stat(inputDir);
    const manStat = await fs.stat(manifestFile);
    return manStat.mtimeMs >= inStat.mtimeMs;
  } catch {
    return false;
  }
}

async function main() {
  let entries;
  try {
    entries = await fs.readdir(inputDir);
  } catch {
    console.warn("optimize-gallery: no src/assets/gallery folder; writing empty manifest.");
    await writeManifest([]);
    return;
  }

  const jpegFiles = entries.filter((f) => /\.jpe?g$/i.test(f)).sort();

  if (jpegFiles.length === 0) {
    console.warn("optimize-gallery: no JPEGs in src/assets/gallery; writing empty manifest.");
    await fs.rm(outDir, { recursive: true, force: true });
    await writeManifest([]);
    return;
  }

  if (await isUpToDate(jpegFiles)) {
    console.log("optimize-gallery: already up to date, skipping.");
    return;
  }

  await fs.mkdir(outDir, { recursive: true });

  const manifest = [];
  let index = 0;

  for (const file of jpegFiles) {
    const inputPath = path.join(inputDir, file);
    const buf = await fs.readFile(inputPath);
    const stem = stemFromFilename(file);

    for (const w of WIDTHS) {
      await sharp(buf)
        .resize({ width: w, height: w, fit: "inside", withoutEnlargement: true })
        .webp({ quality: 82, effort: 4 })
        .toFile(path.join(outDir, `${stem}-${w}.webp`));
    }

    await sharp(buf)
      .resize({ width: 1280, height: 1280, fit: "inside", withoutEnlargement: true })
      .jpeg({ quality: 85, mozjpeg: true })
      .toFile(path.join(outDir, `${stem}-1280.jpg`));

    await sharp(buf)
      .resize({
        width: LIGHTBOX_MAX,
        height: LIGHTBOX_MAX,
        fit: "inside",
        withoutEnlargement: true,
      })
      .webp({ quality: 85, effort: 5 })
      .toFile(path.join(outDir, `${stem}-lightbox.webp`));

    await sharp(buf)
      .resize({
        width: LIGHTBOX_MAX,
        height: LIGHTBOX_MAX,
        fit: "inside",
        withoutEnlargement: true,
      })
      .jpeg({ quality: 88, mozjpeg: true })
      .toFile(path.join(outDir, `${stem}-lightbox.jpg`));

    const baseLabel = file.replace(/\.[^.]+$/i, "");
    const alt = cameraFilenamePattern(baseLabel)
      ? `Gallery photo ${index + 1}`
      : baseLabel.replace(/[-_]/g, " ");

    manifest.push({ stem, alt: alt.replace(/\s+/g, " ").trim() });
    index += 1;
  }

  await writeManifest(manifest);
  console.log(`optimize-gallery: wrote ${manifest.length} images to public/gallery/`);
}

/**
 * @param {{ stem: string; alt: string }[]} rows
 */
async function writeManifest(rows) {
  const lines = rows.map(
    (r) => `  { stem: ${JSON.stringify(r.stem)}, alt: ${JSON.stringify(r.alt)} },`,
  );
  const content = `/** Generated by scripts/optimize-gallery.mjs — do not edit by hand. */
export type GalleryManifestEntry = { stem: string; alt: string }

/** Run \`pnpm optimize:gallery\` after adding/removing files in \`src/assets/gallery/\`. */
export const galleryManifest: GalleryManifestEntry[] = [
${lines.join("\n")}
]
`;
  await fs.writeFile(manifestFile, content, "utf8");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
