/** Generated by scripts/optimize-gallery.mjs — do not edit by hand. */
type GalleryManifestEntry = { stem: string; alt: string }

/** Run `pnpm optimize:gallery` after adding/removing files in `src/assets/gallery/`. */
export const galleryManifest: GalleryManifestEntry[] = [
  { stem: "DSC_0915", alt: "Gallery photo 1" },
  { stem: "DSC_1050", alt: "Gallery photo 2" },
  { stem: "DSC_1146", alt: "Gallery photo 3" },
  { stem: "DSC_1508", alt: "Gallery photo 4" },
  { stem: "DSC_1756", alt: "Gallery photo 5" },
  { stem: "DSC_1855", alt: "Gallery photo 6" },
  { stem: "DSC_1877", alt: "Gallery photo 7" },
  { stem: "DSC_2100", alt: "Gallery photo 8" },
  { stem: "DSC_2111", alt: "Gallery photo 9" },
  { stem: "DSC_2116", alt: "Gallery photo 10" },
  { stem: "DSC_2145", alt: "Gallery photo 11" },
  { stem: "DSC_2147", alt: "Gallery photo 12" },
  { stem: "DSC_2166", alt: "Gallery photo 13" },
  { stem: "DSC_2186", alt: "Gallery photo 14" },
  { stem: "DSC_2205-2", alt: "DSC 2205 (2)" },
  { stem: "DSC_2215", alt: "Gallery photo 16" },
  { stem: "DSC_2284", alt: "Gallery photo 17" },
  { stem: "DSC_2340", alt: "Gallery photo 18" },
  { stem: "DSC_2350", alt: "Gallery photo 19" },
  { stem: "DSC_2663", alt: "Gallery photo 20" },
]
